mountaincar1:
  env_id: MountainCarContinuous-v0
  replay_buffer_size: 100000
  gamma: 0.99 
  tau: 0.005
  policy_noise: 0.02
  noise_clip: 0.5
  policy_freq: 5
  stop_on_reward: -10000.0
  learning_rate: 0.001
  mini_batch_size: 100
  episode_start_reward: 0.0

pendulum1:
  env_id: Pendulum-v1
  replay_buffer_size: 100000
  gamma: 0.99 
  tau: 0.005
  policy_noise: 0.02
  noise_clip: 0.5
  policy_freq: 5
  stop_on_reward: -10000.0
  learning_rate: 0.001
  mini_batch_size: 100
  episode_start_reward: 0.0
  env_make_params:
    g: 7.0

lunarlanding:
  env_id: LunarLander-v2
  replay_buffer_size: 100000
  gamma: 0.99 
  tau: 0.005
  policy_noise: 0.05
  noise_clip: 0.5
  policy_freq: 2
  stop_on_reward: -1000.0
  learning_rate: 0.001
  mini_batch_size: 100
  episode_start_reward: 0.0
  env_make_params:
    continuous: True
    gravity: -5.0
    enable_wind: False
    wind_power: 5.0
    turbulence_power: 1.0

bipedalwalker:
  env_id: BipedalWalker-v3
  replay_buffer_size: 100000
  gamma: 0.99 
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
  stop_on_reward: -1000.0
  learning_rate: 0.001
  mini_batch_size: 100
  episode_start_reward: 0.0
  env_make_params:
    hardcore: False
